services:
  bluemap-db:
    image: mariadb:11
    restart: unless-stopped
    volumes:
      - type: volume
        source: bluemap-db
        target: /var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${BM_ROOT_PASSWORD}
      MARIADB_DATABASE: ${BM_DATABASE}
      MARIADB_USER: ${BM_USER}
      MARIADB_PASSWORD: ${BM_PASSWORD}

volumes:
  bluemap-db: null
